sudo: required
language: node_js
node_js:
- '8'

stages:
- docker release

services:
- docker

install:
- npm install
env:
  global:
  - DOCKER_USER=outsideris
  # DOCKER_PASS
  secure: "j+n6KNDE96PR4Q+69P31zlDtpeO9NoUpxl855xLuItTvB+mxATZoiVp8dq48R3oSWXU6/o9e8orLJO/xOLg8kL38rkijHT8BxwUXSzhC4OsZIIiskMrIuLYId7hWQEUDKdK0WPyUkHN3HORf9tpwtwPzkfrZCGfGofKIgwsTqR9G4BUlYp/UZ7+h6A9WOV0YnnJ65FcKkTBiQNRTX3MPCWXQupULFRaxIJc3t6C1CKtcxLiAq2GsRhn6b0RvFVQE642KFfFXTJEspTafUTW6/uBOrWPaSkoCMrfP5DZ4y11I3AelAJ/dnpefyDl1au5ovuHOGJc9BE70RSZbJ4rYcVCCRf4qUkCVE2zJt0aUVGFRafPeYgvcDDjnRxgYLxZ0JfxH/QR4F1Ty708jm1Ry0ghSFjJwZIaUVMQcv9p+qM3XWbFb01uZRM8IptZ5Tsxoii1frOvdVWrzXwSD16BLX0SYzzAtChFxc2k2OdHEGV9YC7pBjh7PW3UXSkOdgUYmsrMD4SV+5rtZ4IfuY3AH9uT+ao+zWwwrF4gdL/960KpA5sd26hn4sxOeSB+RWe2ICmXJdiBaqgPlASVLfhLGZPQCAJYTzJdP7DwQIQzacXQx3zaxp4KGCg6sZK7Hn0NF22LVuY2ZAgtWhvLNMwguMhK5GbkxR5F1Qz+pBagsJMI="

jobs:
  include:
  - stage: docker release
    script: echo "Deploying Docker image"
    deploy:
      provider: script
      script: bash scripts/docker-deploy.sh
      skip_cleanup: true
      on:
        repo: outsideris/slack-invite-automation
        tags: true
